/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.FrmView;
import controlador.StorageBoxController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author norki
 */

public class FrmBuscarCliente extends javax.swing.JFrame
        implements FrmView<Cliente> {

    private StorageBoxController controller;
    private FrmView<Cliente> view;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBuscarCliente.class.getName());

    /**
     * Creates new form FrmBuscarCliente
     */
    
    public FrmBuscarCliente(StorageBoxController controller,
            FrmView<Cliente> view) {
        initComponents();
        this.controller = controller;
        this.view = view;
        cargarClientes();
    }
 private void cargarClientes() {
        DefaultTableModel modelo =
       (DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
        ArrayList<Cliente> lista =
        new ArrayList<>(controller.listarClientes());
        for (int i = 0; i < lista.size(); i++) {
            Cliente cliente = lista.get(i);
            modelo.addRow(new Object[]{
                cliente.getIdentificacion(),
                cliente.getNombreCompleto(),
                cliente.getTelefono(),
                cliente.getFechaNacimiento(),
                cliente.getCorreoElectronico()
            });
        }
    }
    @Override
    public void clear() {
        txtIdentificacion.setText("");}
    @Override
    public void showData(Cliente data) {
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this,error,"Error",JOptionPane.ERROR_MESSAGE);
    }
    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this,message,"StorageBox",JOptionPane.INFORMATION_MESSAGE
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBuscarCliente = new javax.swing.JLabel();
        lblidentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnMostrarTodos = new javax.swing.JButton();
        scrollClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarCliente.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblBuscarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarCliente.setText("   Buscar cliente ");

        lblidentificacion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        lblidentificacion.setText("Identificacion");

        txtIdentificacion.addActionListener(this::txtIdentificacionActionPerformed);

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(this::btnBuscarClienteActionPerformed);

        btnMostrarTodos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnMostrarTodos.setText("Mostrar todos");
        btnMostrarTodos.addActionListener(this::btnMostrarTodosActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre Completo", "Telefono", "Fecha de Nacimiento", "Correo electrónico"
            }
        ));
        scrollClientes.setViewportView(tblClientes);

        btnAceptar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar ");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostrarTodos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnAceptar)
                        .addGap(51, 51, 51)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarTodos)
                .addGap(18, 18, 18)
                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificacionActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       try {
        String identificacion =
        txtIdentificacion.getText();
        Cliente cliente =
       controller.buscarPorIdentificacion(identificacion);
        if (cliente == null) {
            throw new Exception("No existe un cliente con esa identificación");
        }
        DefaultTableModel modelo =(DefaultTableModel) tblClientes.getModel();
        modelo.setRowCount(0);
        modelo.addRow(new Object[]{
            cliente.getIdentificacion(),
            cliente.getNombreCompleto(),
            cliente.getTelefono(),
            cliente.getFechaNacimiento(),
            cliente.getCorreoElectronico()
        });
    } catch (Exception ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosActionPerformed

    try {
        cargarClientes();
    } catch (Exception ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnMostrarTodosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
    try {
        int fila = tblClientes.getSelectedRow();
        if (fila == -1) {
            throw new Exception("Debe seleccionar un cliente");
        }
        String identificacion =
                tblClientes.getValueAt(fila, 0).toString();
        Cliente cliente =controller.buscarPorIdentificacion(identificacion);
        if (cliente == null) {
            throw new Exception("No se pudo obtener el cliente seleccionado");
        }
        view.showData(cliente);
        setVisible(false);
    } catch (Exception ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    StorageBoxController controller =
            new StorageBoxController();

    FrmBuscarCliente frmBuscarCliente =
            new FrmBuscarCliente(controller, null);

    frmBuscarCliente.setVisible(true);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnMostrarTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBuscarCliente;
    private javax.swing.JLabel lblidentificacion;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtIdentificacion;
    // End of variables declaration//GEN-END:variables
}
