/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.FrmView;
import controlador.StorageBoxController;
import excepciones.DatosInvalidosException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleado;
import modelo.PuestoEmpleado;
/**
 *
 * @author norki
 */
public class FrmEmpleado extends javax.swing.JFrame 
      implements FrmView<Empleado> {
     private StorageBoxController controller;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEmpleado.class.getName());

    /**
     * Creates new form FrmEmpleado
     * @param controller
     */
    public FrmEmpleado(StorageBoxController controller) {
         this.controller = controller;
    initComponents();
    cargarEmpleados();
    }
    private void cargarEmpleados() {
    DefaultTableModel modelo =
            (DefaultTableModel) Empleados_tbl.getModel();
    modelo.setRowCount(0);
    ArrayList<Empleado> lista =
    new ArrayList<>(controller.listarEmpleados());
    for (int i = 0; i < lista.size(); i++) {
        Empleado empleado = lista.get(i);
        modelo.addRow(new Object[]{
            empleado.getIdentificacion(),
            empleado.getNombreCompleto(),
            empleado.getTelefono(),
            empleado.getPuesto(),
            empleado.getSalario()
        });
    }
}
  @Override
public void clear() {
    Id_txt.setText("");
    Nombre_txt.setText("");
    Telefono_txt.setText("");
    Puesto_cbx.setSelectedIndex(0);
    jTextField1.setText("");
}

@Override
public void showData(Empleado data) {
    Id_txt.setText(data.getIdentificacion());
    Nombre_txt.setText(data.getNombreCompleto());
    Telefono_txt.setText(data.getTelefono());
    Puesto_cbx.setSelectedItem(data.getPuesto());
    jTextField1.setText(String.valueOf(data.getSalario()));
}
@Override
public void showError(String error) {
    JOptionPane.showMessageDialog(this,error, "Error", JOptionPane.ERROR_MESSAGE);
}

@Override
public void showMessage(String message) {
    JOptionPane.showMessageDialog(this,message,"StorageBox",JOptionPane.INFORMATION_MESSAGE);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Id_lbl = new javax.swing.JLabel();
        Id_txt = new javax.swing.JTextField();
        Nombre_lbl = new javax.swing.JLabel();
        Nombre_txt = new javax.swing.JTextField();
        Telefono_lbl = new javax.swing.JLabel();
        Telefono_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Empleados_tbl = new javax.swing.JTable();
        Puesto_lbl = new javax.swing.JLabel();
        Puesto_cbx = new javax.swing.JComboBox<>();
        Salario_lbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Empleado");

        Id_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Id_lbl.setText("Identificación");

        Id_txt.addActionListener(this::Id_txtActionPerformed);

        Nombre_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre_lbl.setText("Nombre Completo");

        Nombre_txt.addActionListener(this::Nombre_txtActionPerformed);

        Telefono_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Telefono_lbl.setText("Teléfono");

        Telefono_txt.addActionListener(this::Telefono_txtActionPerformed);

        Empleados_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificación", "Nombre Completo", "Teléfono", "Puesto", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Empleados_tbl);

        Puesto_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Puesto_lbl.setText("Puesto");

        Puesto_cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcionista", "Encargado Bodega", "Mantenimiento", "Operario Carga" }));
        Puesto_cbx.addActionListener(this::Puesto_cbxActionPerformed);

        Salario_lbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Salario_lbl.setText("Salario");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Puesto_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Id_lbl)
                            .addComponent(Id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Puesto_lbl))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Salario_lbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre_lbl)
                                    .addComponent(Nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Telefono_lbl)
                                    .addComponent(Telefono_txt))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre_lbl)
                    .addComponent(Telefono_lbl)
                    .addComponent(Id_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puesto_lbl)
                    .addComponent(Salario_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Puesto_cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_txtActionPerformed

    private void Nombre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_txtActionPerformed

    private void Telefono_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Telefono_txtActionPerformed

    private void Puesto_cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Puesto_cbxActionPerformed
      String puesto =
     Puesto_cbx.getSelectedItem().toString();
    double salario =controller.obtenerSalario(puesto);
    jTextField1.setText(String.valueOf(salario));
    }//GEN-LAST:event_Puesto_cbxActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         try {
        String identificacion = Id_txt.getText();
        String nombreCompleto = Nombre_txt.getText();
        String telefono = Telefono_txt.getText();
        String puesto = Puesto_cbx.getSelectedItem().toString();
        PuestoEmpleado puestoEmpleado =controller.obtenerPuesto(puesto);
        Empleado empleado =new Empleado(identificacion,nombreCompleto,telefono,puestoEmpleado);
        controller.agregarEmpleado(empleado);
        showMessage("Empleado agregado correctamente");
        cargarEmpleados();
        clear();
    } catch (DatosInvalidosException ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       try {
        String identificacion = Id_txt.getText();
        String nombreCompleto = Nombre_txt.getText();
        String telefono = Telefono_txt.getText();
        String puesto = Puesto_cbx.getSelectedItem().toString();
        PuestoEmpleado puestoEmpleado =controller.obtenerPuesto(puesto);
        controller.actualizarEmpleado(identificacion,nombreCompleto,telefono,puestoEmpleado);
        showMessage("Empleado actualizado correctamente");
        cargarEmpleados();
        clear();
    } catch (DatosInvalidosException ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
        String identificacion = Id_txt.getText();
        controller.eliminarEmpleado(identificacion);
        showMessage("Empleado eliminado correctamente");
        cargarEmpleados();
        clear();
    } catch (DatosInvalidosException ex) {
        showError(ex.getMessage());
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
          clear();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    BuscarEmpleado buscarEmpleado =
    new BuscarEmpleado(controller, this);
    buscarEmpleado.setVisible(true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         StorageBoxController controller =
            new StorageBoxController();
    FrmEmpleado frmEmpleado =
     new FrmEmpleado(controller);
    frmEmpleado.setVisible(true);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Empleados_tbl;
    private javax.swing.JLabel Id_lbl;
    private javax.swing.JTextField Id_txt;
    private javax.swing.JLabel Nombre_lbl;
    private javax.swing.JTextField Nombre_txt;
    private javax.swing.JComboBox<String> Puesto_cbx;
    private javax.swing.JLabel Puesto_lbl;
    private javax.swing.JLabel Salario_lbl;
    private javax.swing.JLabel Telefono_lbl;
    private javax.swing.JTextField Telefono_txt;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
